import { ModalProvider } from '@/provider/modal-provider'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar/nav'
import { getCurrentUser } from './actions/getCurrentUser'
import ToasterProvider from '@/provider/ToastProvider'
import Alert from '@/components/Visible'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body className={inter.className}>
        <Alert />
        <ToasterProvider />
        <Navbar currentUser={currentUser?.currentUser} />
        <ModalProvider />

        {children}
      </body>
    </html>
  )
}
